# Generated by Django 5.0.4 on 2024-05-13 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservApp', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='chambre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservApp.chambre'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
